### ISSUE TITLE
ctrl7 is added more times than required

### ISSUE THREAD

**Issue by ketchupok** [cosmoproject/cosmo-dsp#6]
When testing with "Test_All_UDO-to-JSON-to-csd.py" it happens for MultiDelay.json.csd.

**Comment by berntisak** [comment]
The code in CosmoPatcherGraph.py works. Something wrong with the code in Test_All_UDO-to-JSON-to-csd.py

**Comment by ketchupok** [comment]
fixed, by removing midi_ctrls[] in CosmoPatcherGraph.py
